import type { AppConfig } from '../types';

export const defaultConfig: AppConfig = {
  email: 'email@domain.com',
  password: 'yourpassword',
  openaiApiKey: '',
  disableAntiLock: false,
  remote: false,
  residentStatus: false,
  lessApplicantsEnabled: false,
  lessApplicantsCount: 100,
  newestPostingsFirst: true,
  experienceLevel: {
    internship: false,
    entry: true,
    associate: true,
    'mid-senior_level': true,
    director: false,
    executive: false,
  },
  jobTypes: {
    'full-time': true,
    contract: true,
    'part-time': false,
    temporary: true,
    internship: false,
    other: false,
    volunteer: false,
  },
  date: {
    'all_time': true,
    month: false,
    week: false,
    '24_hours': false,
    custom_hours: false,
  },
  positionsWithCount: [{ name: 'engineer', count: 100 }],
  locations: ['united states'],
  distance: 100,
  outputFileDirectory: '~/Documents/EasyApplyBot/',
  companyBlacklist: [],
  titleBlacklist: [],
  posterBlacklist: [],
  uploads: {
    resume: '/home/user/resume.pdf',
    coverLetter: '/home/user/coverLetter.pdf',
    photo: '',
  },
  checkboxes: {
    driversLicence: true,
    requireVisa: false,
    legallyAuthorized: false,
    certifiedProfessional: true,
    urgentFill: true,
    commute: true,
    remote: true,
    drugTest: true,
    assessment: true,
    securityClearance: false,
    degreeCompleted: ['High School Diploma', "Bachelor's Degree"],
    backgroundCheck: true,
  },
  universityGpa: 4.0,
  salaryMinimum: 65000,
  customHours: 1,
  languages: [
    { name: 'english', proficiency: 'Native or bilingual' },
    { name: 'chinese', proficiency: 'Native or bilingual' },
  ],
  noticePeriod: 2,
  experience: [
    { name: 'default', years: 0 },
    { name: 'Accounting/Auditing', years: 0 },
    { name: 'Administrative', years: 0 },
    { name: 'Advertising', years: 0 },
    { name: 'Analyst', years: 0 },
    { name: 'Art/Creative', years: 0 },
    { name: 'Business Development', years: 0 },
    { name: 'Consulting', years: 0 },
    { name: 'Customer Service', years: 0 },
    { name: 'Distribution Design', years: 0 },
    { name: 'Education', years: 0 },
    { name: 'Engineering', years: 0 },
    { name: 'Finance', years: 0 },
    { name: 'General Business', years: 0 },
    { name: 'Health Care Provider', years: 0 },
    { name: 'Human Resources', years: 0 },
    { name: 'Information Technology', years: 0 },
    { name: 'Legal', years: 0 },
    { name: 'Management', years: 0 },
    { name: 'Manufacturing', years: 0 },
    { name: 'Marketing', years: 0 },
    { name: 'Public Relations', years: 0 },
    { name: 'Purchasing', years: 0 },
    { name: 'Product Management', years: 0 },
    { name: 'Project Management', years: 0 },
    { name: 'Production', years: 0 },
    { name: 'Quality Assurance', years: 0 },
    { name: 'Research', years: 0 },
    { name: 'Sales', years: 0 },
    { name: 'Science', years: 0 },
    { name: 'Strategy/Planning', years: 0 },
    { name: 'Supply Chain', years: 0 },
    { name: 'Training', years: 0 },
    { name: 'Writing/Editing', years: 0 },
    { name: 'VBA', years: 0 },
    { name: 'PowerBI', years: 0 },
    { name: 'PowerQuery', years: 0 },
    { name: 'Excel', years: 0 },
    { name: 'PowerPoint', years: 0 },
    { name: 'Word', years: 0 },
    { name: 'SQL Server', years: 0 },
    { name: 'Communication', years: 0 },
    { name: 'Financial markets', years: 0 },
    { name: 'Business', years: 0 },
    { name: 'Financial services', years: 0 },
    { name: 'Team leadership', years: 0 },
    { name: 'Cash flow', years: 0 },
    { name: 'Hedging', years: 0 },
    { name: 'Treasury services', years: 0 },
    { name: 'Microsoft Power BI', years: 0 },
    { name: 'Accounting', years: 0 },
    { name: 'Auditing', years: 0 },
    { name: 'Financial modeling', years: 0 },
    { name: 'Budgeting & forecasting', years: 0 },
    { name: 'FP&A', years: 0 },
    { name: 'PQE', years: 0 },
    { name: 'Training & Development', years: 0 },
    { name: 'Python', years: 5 },
    { name: 'Java', years: 5 },
  ],
  personalInfo: {
    Pronouns: 'Mr.',
    'First Name': 'FirstName',
    'Last Name': 'LastName',
    'Phone Country Code': 'Canada (+1)',
    'Mobile Phone Number': '1234567890',
    'Street address': '123 Fake Street',
    City: 'Red Deer, Alberta',
    State: 'YourState',
    Zip: 'YourZip/Postal',
    Linkedin: 'https://www.linkedin.com/in/my-linkedin-profile',
    Website: 'https://www.my-website.com',
    MessageToManager:
      'Hi, I am interested to join your organization. Please have a look at my resume. Thank you.',
  },
  eeo: {
    gender: 'Male',
    race: 'Asian',
    veteran: 'I am not a protected veteran',
    disability: 'No, I do not have a disability and have not had one in the past',
  },
  textResume: '/home/user/简历.txt',
  evaluateJobFit: false,
  jobFitPrompt: 'You are evaluating job fit for technical roles.\nRecommend APPLY if:\n- Candidate meets 65 percent of the core requirements\n- Experience gap is 2 years or less\n- Has relevant transferable skills\n\nReturn SKIP if:\n- Experience gap is greater than 2 years\n- Missing multiple core requirements\n- Role is clearly more senior\n- The role is focused on an uncommon technology or skill that is required and that the candidate does not have experience with\n- The role is a leadership role or a role that requires managing people and the candidate has no experience leading or managing people',
  debug: false,
  customQuestions: [
    {
      question:
        'Would you like to receive emails, text messages, or phone calls about this job and other matchingopportunities?',
      answer: 'yes',
    },
    {
      question: 'Are you legally authorized to work in the United States?',
      answer: 'yes',
    },
    { question: 'Do you have a green card and citizenship?', answer: 'yes' },
    {
      question:
        'If applying from outside our area, are you willing to pay your own relocation expenses?',
      answer: 'yes',
    },
    {
      question:
        'Are you willing to travel 50% or more as needed for business needs?',
      answer: 'yes',
    },
    {
      question:
        'Are you professional with power distribution and lighting systems design?',
      answer: 'no',
    },
    {
      question: 'Are you authorized to work in the United States?',
      answer: 'yes',
    },
    {
      question: 'How would you describe your sexual orientation?',
      answer: 'Heterosexual',
    },
    { question: 'Do you identify as transgender?', answer: 'no' },
  ],
  useCloudAI: true,
  educations: [
    {
      school: 'Lehigh university',
      city: 'Bethlehem',
      degree: ' Bachelor of science ',
      major: 'Computer Science',
      from_month: 'September',
      from_year: '2019',
      to_month: 'May',
      to_year: '2023',
      current: false,
    },
  ],
  workExperiences: [
    {
      title: 'CO-FOUNDER & ENGINEER ',
      company: 'XXX',
      city: 'San Francisco',
      description: 'XXXX',
      from_month: 'December',
      from_year: '2022',
      to_month: 'Month',
      to_year: 'Year',
      current: true,
    },
    {
      title: 'APPLICATION ENGINEER',
      company: 'XXXX',
      city: 'San Francisco',
      description: 'xxxx',
      from_month: 'August',
      from_year: '2022',
      to_month: 'August',
      to_year: '2023',
      current: false,
    },
  ],
  speed_mode: 'slow',
}; 