import type { AppConfig } from '../types';

export const defaultConfig: AppConfig = {
  email: 'email@domain.com',
  password: 'yourpassword',
  openaiApiKey: '',
  disableAntiLock: false,
  remote: false,
  residentStatus: false,
  lessApplicantsEnabled: false,
  lessApplicantsCount: 100,
  newestPostingsFirst: true,
  experienceLevel: {
    internship: false,
    entry: true,
    associate: true,
    'mid-senior_level': true,
    director: false,
    executive: false,
  },
  jobTypes: {
    'full-time': true,
    contract: true,
    'part-time': false,
    temporary: true,
    internship: false,
    other: false,
    volunteer: false,
  },
  date: {
    'all_time': true,
    month: false,
    week: false,
    '24_hours': false,
    custom_hours: false,
  },
  positionsWithCount: [{ name: 'engineer', count: 100 }],
  locations: ['united states'],
  distance: 100,
  outputFileDirectory: '~/Documents/EasyApplyBot/',
  companyBlacklist: [],
  titleBlacklist: [],
  posterBlacklist: [],
//   uploads: {
//     resume: '/home/user/resume.pdf',
//     coverLetter: '/home/user/coverLetter.pdf',
//     photo: '',
//   },
  checkboxes: {
    driversLicence: true,
    requireVisa: false,
    legallyAuthorized: false,
    certifiedProfessional: true,
    urgentFill: true,
    commute: true,
    remote: true,
    drugTest: true,
    assessment: true,
    securityClearance: false,
    degreeCompleted: ['High School Diploma', "Bachelor's Degree", "Master's Degree"],
    backgroundCheck: true,
  },
  universityGpa: 4.0,
  salaryMinimum: 65000,
  customHours: 1,
  languages: {
    english: 'Native or bilingual',
    chinese: 'Native or bilingual',
  },
  noticePeriod: 2,
  experience: {
    default: 0,
    'Full Stack Development': 1,
    'Mobile and Web Applications': 1,
    'Object-Oriented Programming': 1,
    'Agile Development & Best Practices': 1,
    'API Integration & Compliance': 1,
    'Secure Payment Processing': 1,
  },
  personalInfo: {
    Pronouns: 'Mr.',
    'First Name': 'FirstName',
    'Last Name': 'LastName',
    'Phone Country Code': 'Canada (+1)',
    'Mobile Phone Number': '1234567890',
    'Street address': '123 Fake Street',
    City: 'Red Deer, Alberta',
    State: 'YourState',
    Zip: 'YourZip/Postal',
    Linkedin: 'https://www.linkedin.com/in/my-linkedin-profile',
    Website: 'https://www.my-website.com',
    MessageToManager:
      'Hi, I am interested to join your organization. Please have a look at my resume. Thank you.',
  },
  eeo: {
    gender: 'Male',
    race: 'Asian',
    veteran: 'I am not a protected veteran',
    disability: 'No, I do not have a disability and have not had one in the past',
  },
//   textResume: '/home/user/简历.txt',
  evaluateJobFit: false,
  jobFitPrompt: 'You are evaluating job fit for technical roles.\nRecommend APPLY if:\n- Candidate meets 65 percent of the core requirements\n- Experience gap is 2 years or less\n- Has relevant transferable skills\n\nReturn SKIP if:\n- Experience gap is greater than 2 years\n- Missing multiple core requirements\n- Role is clearly more senior\n- The role is focused on an uncommon technology or skill that is required and that the candidate does not have experience with\n- The role is a leadership role or a role that requires managing people and the candidate has no experience leading or managing people',
  debug: false,
  customQuestions: {
    'Would you like to receive emails, text messages, or phone calls about this job and other matchingopportunities?':
      'yes',
    'Are you legally authorized to work in the United States?': 'yes',
    'Do you have a green card and citizenship?': 'yes',
    'If applying from outside our area, are you willing to pay your own relocation expenses?':
      'yes',
    'Are you willing to travel 50% or more as needed for business needs?': 'yes',
    'Are you professional with power distribution and lighting systems design?':
      'no',
    'How would you describe your sexual orientation?': 'Heterosexual',
    'Do you identify as transgender?': 'no',
  },
  useCloudAI: true,
  educations: [
    {
      school: 'University of California, Berkeley',
      city: 'Berkeley',
      degree: 'Bachelor of Science',
      major: 'Computer Science',
      from_month: 'August',
      from_year: '2018',
      to_month: 'May',
      to_year: '2022',
      current: false,
    },
    {
      school: 'Stanford University',
      city: 'Stanford',
      degree: 'Master of Science',
      major: 'Artificial Intelligence',
      from_month: 'September',
      from_year: '2022',
      to_month: 'June',
      to_year: '2024',
      current: false,
    },
  ],
  workExperiences: [
    {
      title: 'Senior Software Engineer',
      company: 'Google',
      city: 'Mountain View',
      description: 'Led development of machine learning infrastructure for Search ranking algorithms. Implemented scalable data pipelines processing 10B+ queries daily. Collaborated with cross-functional teams to optimize system performance and reduce latency by 25%. Mentored 3 junior engineers and contributed to architectural decisions for next-generation ML platform.',
      from_month: 'July',
      from_year: '2024',
      to_month: '',
      to_year: '',
      current: true,
    },
    {
      title: 'Software Engineering Intern',
      company: 'Meta',
      city: 'Menlo Park',
      description: "Developed React components for Instagram's content discovery feature, improving user engagement by 15%. Built RESTful APIs using Node.js and GraphQL for real-time data synchronization. Participated in code reviews and followed Agile development practices. Presented final project to engineering leadership team.",
      from_month: 'June',
      from_year: '2023',
      to_month: 'August',
      to_year: '2023',
      current: false,
    },
    {
      title: 'Research Assistant',
      company: 'Stanford AI Lab',
      city: 'Stanford',
      description: 'Conducted research on natural language processing and computer vision under Professor Andrew Ng. Published 2 papers in top-tier conferences (ICML, NIPS). Implemented deep learning models using PyTorch and TensorFlow. Collaborated with PhD students on groundbreaking research in multimodal AI systems.',
      from_month: 'September',
      from_year: '2022',
      to_month: 'May',
      to_year: '2024',
      current: false,
    },
  ],
  speed_mode: 'slow',
}; 