import type { FieldOption } from '../types';

export const countryCodeOptions: FieldOption[] = [
  { key: "Select an option", value: "Select an option", en_label: "Select an option", zh_label: "请选择一个选项" },
  { key: "Canada (+1)", value: "Canada (+1)", en_label: "Canada (+1)", zh_label: "Canada (+1)" },
  { key: "United States (+1)", value: "United States (+1)", en_label: "United States (+1)", zh_label: "United States (+1)" },
  { key: "Afghanistan (+93)", value: "Afghanistan (+93)", en_label: "Afghanistan (+93)", zh_label: "Afghanistan (+93)" },
  { key: "Aland Islands (+358)", value: "Aland Islands (+358)", en_label: "Aland Islands (+358)", zh_label: "Aland Islands (+358)" },
  { key: "Albania (+355)", value: "Albania (+355)", en_label: "Albania (+355)", zh_label: "Albania (+355)" },
  { key: "Algeria (+213)", value: "Algeria (+213)", en_label: "Algeria (+213)", zh_label: "Algeria (+213)" },
  { key: "American Samoa (+1)", value: "American Samoa (+1)", en_label: "American Samoa (+1)", zh_label: "American Samoa (+1)" },
  { key: "Andorra (+376)", value: "Andorra (+376)", en_label: "Andorra (+376)", zh_label: "Andorra (+376)" },
  { key: "Angola (+244)", value: "Angola (+244)", en_label: "Angola (+244)", zh_label: "Angola (+244)" },
  { key: "Anguilla (+1)", value: "Anguilla (+1)", en_label: "Anguilla (+1)", zh_label: "Anguilla (+1)" },
  { key: "Antarctica (+0)", value: "Antarctica (+0)", en_label: "Antarctica (+0)", zh_label: "Antarctica (+0)" },
  { key: "Antigua and Barbuda (+1)", value: "Antigua and Barbuda (+1)", en_label: "Antigua and Barbuda (+1)", zh_label: "Antigua and Barbuda (+1)" },
  { key: "Argentina (+54)", value: "Argentina (+54)", en_label: "Argentina (+54)", zh_label: "Argentina (+54)" },
  { key: "Armenia (+374)", value: "Armenia (+374)", en_label: "Armenia (+374)", zh_label: "Armenia (+374)" },
  { key: "Aruba (+297)", value: "Aruba (+297)", en_label: "Aruba (+297)", zh_label: "Aruba (+297)" },
  { key: "Australia (+61)", value: "Australia (+61)", en_label: "Australia (+61)", zh_label: "Australia (+61)" },
  { key: "Austria (+43)", value: "Austria (+43)", en_label: "Austria (+43)", zh_label: "Austria (+43)" },
  { key: "Azerbaijan (+994)", value: "Azerbaijan (+994)", en_label: "Azerbaijan (+994)", zh_label: "Azerbaijan (+994)" },
  { key: "Bahamas (+1)", value: "Bahamas (+1)", en_label: "Bahamas (+1)", zh_label: "Bahamas (+1)" },
  { key: "Bahrain (+973)", value: "Bahrain (+973)", en_label: "Bahrain (+973)", zh_label: "Bahrain (+973)" },
  { key: "Bangladesh (+880)", value: "Bangladesh (+880)", en_label: "Bangladesh (+880)", zh_label: "Bangladesh (+880)" },
  { key: "Barbados (+1)", value: "Barbados (+1)", en_label: "Barbados (+1)", zh_label: "Barbados (+1)" },
  { key: "Belarus (+375)", value: "Belarus (+375)", en_label: "Belarus (+375)", zh_label: "Belarus (+375)" },
  { key: "Belgium (+32)", value: "Belgium (+32)", en_label: "Belgium (+32)", zh_label: "Belgium (+32)" },
  { key: "Belize (+501)", value: "Belize (+501)", en_label: "Belize (+501)", zh_label: "Belize (+501)" },
  { key: "Benin (+229)", value: "Benin (+229)", en_label: "Benin (+229)", zh_label: "Benin (+229)" },
  { key: "Bermuda (+1)", value: "Bermuda (+1)", en_label: "Bermuda (+1)", zh_label: "Bermuda (+1)" },
  { key: "Bhutan (+975)", value: "Bhutan (+975)", en_label: "Bhutan (+975)", zh_label: "Bhutan (+975)" },
  { key: "Bolivia (+591)", value: "Bolivia (+591)", en_label: "Bolivia (+591)", zh_label: "Bolivia (+591)" },
  { key: "Bosnia and Herzegovina (+387)", value: "Bosnia and Herzegovina (+387)", en_label: "Bosnia and Herzegovina (+387)", zh_label: "Bosnia and Herzegovina (+387)" },
  { key: "Botswana (+267)", value: "Botswana (+267)", en_label: "Botswana (+267)", zh_label: "Botswana (+267)" },
  { key: "Bouvet Island (+0)", value: "Bouvet Island (+0)", en_label: "Bouvet Island (+0)", zh_label: "Bouvet Island (+0)" },
  { key: "Brazil (+55)", value: "Brazil (+55)", en_label: "Brazil (+55)", zh_label: "Brazil (+55)" },
  { key: "British Indian Ocean Territory (+246)", value: "British Indian Ocean Territory (+246)", en_label: "British Indian Ocean Territory (+246)", zh_label: "British Indian Ocean Territory (+246)" },
  { key: "Brunei Darussalam (+673)", value: "Brunei Darussalam (+673)", en_label: "Brunei Darussalam (+673)", zh_label: "Brunei Darussalam (+673)" },
  { key: "Bulgaria (+359)", value: "Bulgaria (+359)", en_label: "Bulgaria (+359)", zh_label: "Bulgaria (+359)" },
  { key: "Burkina Faso (+226)", value: "Burkina Faso (+226)", en_label: "Burkina Faso (+226)", zh_label: "Burkina Faso (+226)" },
  { key: "Burundi (+257)", value: "Burundi (+257)", en_label: "Burundi (+257)", zh_label: "Burundi (+257)" },
  { key: "Cambodia (+855)", value: "Cambodia (+855)", en_label: "Cambodia (+855)", zh_label: "Cambodia (+855)" },
  { key: "Cameroon (+237)", value: "Cameroon (+237)", en_label: "Cameroon (+237)", zh_label: "Cameroon (+237)" },
  { key: "Cape Verde (+238)", value: "Cape Verde (+238)", en_label: "Cape Verde (+238)", zh_label: "Cape Verde (+238)" },
  { key: "Caribbean Nations (+0)", value: "Caribbean Nations (+0)", en_label: "Caribbean Nations (+0)", zh_label: "Caribbean Nations (+0)" },
  { key: "Cayman Islands (+1)", value: "Cayman Islands (+1)", en_label: "Cayman Islands (+1)", zh_label: "Cayman Islands (+1)" },
  { key: "Central African Republic (+236)", value: "Central African Republic (+236)", en_label: "Central African Republic (+236)", zh_label: "Central African Republic (+236)" },
  { key: "Chad (+235)", value: "Chad (+235)", en_label: "Chad (+235)", zh_label: "Chad (+235)" },
  { key: "Chile (+56)", value: "Chile (+56)", en_label: "Chile (+56)", zh_label: "Chile (+56)" },
  { key: "China (+86)", value: "China (+86)", en_label: "China (+86)", zh_label: "China (+86)" },
  { key: "Christmas Island (+61)", value: "Christmas Island (+61)", en_label: "Christmas Island (+61)", zh_label: "Christmas Island (+61)" },
  { key: "Cocos (Keeling) Islands (+61)", value: "Cocos (Keeling) Islands (+61)", en_label: "Cocos (Keeling) Islands (+61)", zh_label: "Cocos (Keeling) Islands (+61)" },
  { key: "Colombia (+57)", value: "Colombia (+57)", en_label: "Colombia (+57)", zh_label: "Colombia (+57)" },
  { key: "Comoros (+269)", value: "Comoros (+269)", en_label: "Comoros (+269)", zh_label: "Comoros (+269)" },
  { key: "Congo (+242)", value: "Congo (+242)", en_label: "Congo (+242)", zh_label: "Congo (+242)" },
  { key: "Cook Islands (+682)", value: "Cook Islands (+682)", en_label: "Cook Islands (+682)", zh_label: "Cook Islands (+682)" },
  { key: "Costa Rica (+506)", value: "Costa Rica (+506)", en_label: "Costa Rica (+506)", zh_label: "Costa Rica (+506)" },
  { key: "Cote D'Ivoire (Ivory Coast) (+225)", value: "Cote D'Ivoire (Ivory Coast) (+225)", en_label: "Cote D'Ivoire (Ivory Coast) (+225)", zh_label: "Cote D'Ivoire (Ivory Coast) (+225)" },
  { key: "Croatia (+385)", value: "Croatia (+385)", en_label: "Croatia (+385)", zh_label: "Croatia (+385)" },
  { key: "Cuba (+53)", value: "Cuba (+53)", en_label: "Cuba (+53)", zh_label: "Cuba (+53)" },
  { key: "Cyprus (+357)", value: "Cyprus (+357)", en_label: "Cyprus (+357)", zh_label: "Cyprus (+357)" },
  { key: "Czech Republic (+420)", value: "Czech Republic (+420)", en_label: "Czech Republic (+420)", zh_label: "Czech Republic (+420)" },
  { key: "Democratic Republic of the Congo (+243)", value: "Democratic Republic of the Congo (+243)", en_label: "Democratic Republic of the Congo (+243)", zh_label: "Democratic Republic of the Congo (+243)" },
  { key: "Denmark (+45)", value: "Denmark (+45)", en_label: "Denmark (+45)", zh_label: "Denmark (+45)" },
  { key: "Djibouti (+253)", value: "Djibouti (+253)", en_label: "Djibouti (+253)", zh_label: "Djibouti (+253)" },
  { key: "Dominica (+1)", value: "Dominica (+1)", en_label: "Dominica (+1)", zh_label: "Dominica (+1)" },
  { key: "Dominican Republic (+1)", value: "Dominican Republic (+1)", en_label: "Dominican Republic (+1)", zh_label: "Dominican Republic (+1)" },
  { key: "Ecuador (+593)", value: "Ecuador (+593)", en_label: "Ecuador (+593)", zh_label: "Ecuador (+593)" },
  { key: "Egypt (+20)", value: "Egypt (+20)", en_label: "Egypt (+20)", zh_label: "Egypt (+20)" },
  { key: "El Salvador (+503)", value: "El Salvador (+503)", en_label: "El Salvador (+503)", zh_label: "El Salvador (+503)" },
  { key: "Equatorial Guinea (+240)", value: "Equatorial Guinea (+240)", en_label: "Equatorial Guinea (+240)", zh_label: "Equatorial Guinea (+240)" },
  { key: "Eritrea (+291)", value: "Eritrea (+291)", en_label: "Eritrea (+291)", zh_label: "Eritrea (+291)" },
  { key: "Estonia (+372)", value: "Estonia (+372)", en_label: "Estonia (+372)", zh_label: "Estonia (+372)" },
  { key: "Ethiopia (+251)", value: "Ethiopia (+251)", en_label: "Ethiopia (+251)", zh_label: "Ethiopia (+251)" },
  { key: "Falkland Islands (Malvinas) (+500)", value: "Falkland Islands (Malvinas) (+500)", en_label: "Falkland Islands (Malvinas) (+500)", zh_label: "Falkland Islands (Malvinas) (+500)" },
  { key: "Faroe Islands (+298)", value: "Faroe Islands (+298)", en_label: "Faroe Islands (+298)", zh_label: "Faroe Islands (+298)" },
  { key: "Federated States of Micronesia (+691)", value: "Federated States of Micronesia (+691)", en_label: "Federated States of Micronesia (+691)", zh_label: "Federated States of Micronesia (+691)" },
  { key: "Fiji (+679)", value: "Fiji (+679)", en_label: "Fiji (+679)", zh_label: "Fiji (+679)" },
  { key: "Finland (+358)", value: "Finland (+358)", en_label: "Finland (+358)", zh_label: "Finland (+358)" },
  { key: "France (+33)", value: "France (+33)", en_label: "France (+33)", zh_label: "France (+33)" },
  { key: "French Guiana (+594)", value: "French Guiana (+594)", en_label: "French Guiana (+594)", zh_label: "French Guiana (+594)" },
  { key: "French Polynesia (+689)", value: "French Polynesia (+689)", en_label: "French Polynesia (+689)", zh_label: "French Polynesia (+689)" },
  { key: "French Southern Territories (+0)", value: "French Southern Territories (+0)", en_label: "French Southern Territories (+0)", zh_label: "French Southern Territories (+0)" },
  { key: "Gabon (+241)", value: "Gabon (+241)", en_label: "Gabon (+241)", zh_label: "Gabon (+241)" },
  { key: "Gambia (+220)", value: "Gambia (+220)", en_label: "Gambia (+220)", zh_label: "Gambia (+220)" },
  { key: "Georgia (+995)", value: "Georgia (+995)", en_label: "Georgia (+995)", zh_label: "Georgia (+995)" },
  { key: "Germany (+49)", value: "Germany (+49)", en_label: "Germany (+49)", zh_label: "Germany (+49)" },
  { key: "Ghana (+233)", value: "Ghana (+233)", en_label: "Ghana (+233)", zh_label: "Ghana (+233)" },
  { key: "Gibraltar (+350)", value: "Gibraltar (+350)", en_label: "Gibraltar (+350)", zh_label: "Gibraltar (+350)" },
  { key: "Greece (+30)", value: "Greece (+30)", en_label: "Greece (+30)", zh_label: "Greece (+30)" },
  { key: "Greenland (+299)", value: "Greenland (+299)", en_label: "Greenland (+299)", zh_label: "Greenland (+299)" },
  { key: "Grenada (+1)", value: "Grenada (+1)", en_label: "Grenada (+1)", zh_label: "Grenada (+1)" },
  { key: "Guadeloupe (+590)", value: "Guadeloupe (+590)", en_label: "Guadeloupe (+590)", zh_label: "Guadeloupe (+590)" },
  { key: "Guam (+1)", value: "Guam (+1)", en_label: "Guam (+1)", zh_label: "Guam (+1)" },
  { key: "Guatemala (+502)", value: "Guatemala (+502)", en_label: "Guatemala (+502)", zh_label: "Guatemala (+502)" },
  { key: "Guernsey (+44)", value: "Guernsey (+44)", en_label: "Guernsey (+44)", zh_label: "Guernsey (+44)" },
  { key: "Guinea (+224)", value: "Guinea (+224)", en_label: "Guinea (+224)", zh_label: "Guinea (+224)" },
  { key: "Guinea-Bissau (+245)", value: "Guinea-Bissau (+245)", en_label: "Guinea-Bissau (+245)", zh_label: "Guinea-Bissau (+245)" },
  { key: "Guyana (+592)", value: "Guyana (+592)", en_label: "Guyana (+592)", zh_label: "Guyana (+592)" },
  { key: "Haiti (+509)", value: "Haiti (+509)", en_label: "Haiti (+509)", zh_label: "Haiti (+509)" },
  { key: "Heard Island and McDonald Islands (+0)", value: "Heard Island and McDonald Islands (+0)", en_label: "Heard Island and McDonald Islands (+0)", zh_label: "Heard Island and McDonald Islands (+0)" },
  { key: "Honduras (+504)", value: "Honduras (+504)", en_label: "Honduras (+504)", zh_label: "Honduras (+504)" },
  { key: "Hong Kong (+852)", value: "Hong Kong (+852)", en_label: "Hong Kong (+852)", zh_label: "Hong Kong (+852)" },
  { key: "Hungary (+36)", value: "Hungary (+36)", en_label: "Hungary (+36)", zh_label: "Hungary (+36)" },
  { key: "Iceland (+354)", value: "Iceland (+354)", en_label: "Iceland (+354)", zh_label: "Iceland (+354)" },
  { key: "India (+91)", value: "India (+91)", en_label: "India (+91)", zh_label: "India (+91)" },
  { key: "Indonesia (+62)", value: "Indonesia (+62)", en_label: "Indonesia (+62)", zh_label: "Indonesia (+62)" },
  { key: "Iran (+98)", value: "Iran (+98)", en_label: "Iran (+98)", zh_label: "Iran (+98)" },
  { key: "Iraq (+964)", value: "Iraq (+964)", en_label: "Iraq (+964)", zh_label: "Iraq (+964)" },
  { key: "Ireland (+353)", value: "Ireland (+353)", en_label: "Ireland (+353)", zh_label: "Ireland (+353)" },
  { key: "Isle of Man (+44)", value: "Isle of Man (+44)", en_label: "Isle of Man (+44)", zh_label: "Isle of Man (+44)" },
  { key: "Israel (+972)", value: "Israel (+972)", en_label: "Israel (+972)", zh_label: "Israel (+972)" },
  { key: "Italy (+39)", value: "Italy (+39)", en_label: "Italy (+39)", zh_label: "Italy (+39)" },
  { key: "Jamaica (+1)", value: "Jamaica (+1)", en_label: "Jamaica (+1)", zh_label: "Jamaica (+1)" },
  { key: "Japan (+81)", value: "Japan (+81)", en_label: "Japan (+81)", zh_label: "Japan (+81)" },
  { key: "Jersey (+44)", value: "Jersey (+44)", en_label: "Jersey (+44)", zh_label: "Jersey (+44)" },
  { key: "Jordan (+962)", value: "Jordan (+962)", en_label: "Jordan (+962)", zh_label: "Jordan (+962)" },
  { key: "Kazakhstan (+7)", value: "Kazakhstan (+7)", en_label: "Kazakhstan (+7)", zh_label: "Kazakhstan (+7)" },
  { key: "Kenya (+254)", value: "Kenya (+254)", en_label: "Kenya (+254)", zh_label: "Kenya (+254)" },
  { key: "Kiribati (+686)", value: "Kiribati (+686)", en_label: "Kiribati (+686)", zh_label: "Kiribati (+686)" },
  { key: "Korea (+82)", value: "Korea (+82)", en_label: "Korea (+82)", zh_label: "Korea (+82)" },
  { key: "Korea (North) (+850)", value: "Korea (North) (+850)", en_label: "Korea (North) (+850)", zh_label: "Korea (North) (+850)" },
  { key: "Kosovo (+383)", value: "Kosovo (+383)", en_label: "Kosovo (+383)", zh_label: "Kosovo (+383)" },
  { key: "Kuwait (+965)", value: "Kuwait (+965)", en_label: "Kuwait (+965)", zh_label: "Kuwait (+965)" },
  { key: "Kyrgyzstan (+996)", value: "Kyrgyzstan (+996)", en_label: "Kyrgyzstan (+996)", zh_label: "Kyrgyzstan (+996)" },
  { key: "Laos (+856)", value: "Laos (+856)", en_label: "Laos (+856)", zh_label: "Laos (+856)" },
  { key: "Latvia (+371)", value: "Latvia (+371)", en_label: "Latvia (+371)", zh_label: "Latvia (+371)" },
  { key: "Lebanon (+961)", value: "Lebanon (+961)", en_label: "Lebanon (+961)", zh_label: "Lebanon (+961)" },
  { key: "Lesotho (+266)", value: "Lesotho (+266)", en_label: "Lesotho (+266)", zh_label: "Lesotho (+266)" },
  { key: "Liberia (+231)", value: "Liberia (+231)", en_label: "Liberia (+231)", zh_label: "Liberia (+231)" },
  { key: "Libya (+218)", value: "Libya (+218)", en_label: "Libya (+218)", zh_label: "Libya (+218)" },
  { key: "Liechtenstein (+423)", value: "Liechtenstein (+423)", en_label: "Liechtenstein (+423)", zh_label: "Liechtenstein (+423)" },
  { key: "Lithuania (+370)", value: "Lithuania (+370)", en_label: "Lithuania (+370)", zh_label: "Lithuania (+370)" },
  { key: "Luxembourg (+352)", value: "Luxembourg (+352)", en_label: "Luxembourg (+352)", zh_label: "Luxembourg (+352)" },
  { key: "Macao (+853)", value: "Macao (+853)", en_label: "Macao (+853)", zh_label: "Macao (+853)" },
  { key: "Macedonia (+389)", value: "Macedonia (+389)", en_label: "Macedonia (+389)", zh_label: "Macedonia (+389)" },
  { key: "Madagascar (+261)", value: "Madagascar (+261)", en_label: "Madagascar (+261)", zh_label: "Madagascar (+261)" },
  { key: "Malawi (+265)", value: "Malawi (+265)", en_label: "Malawi (+265)", zh_label: "Malawi (+265)" },
  { key: "Malaysia (+60)", value: "Malaysia (+60)", en_label: "Malaysia (+60)", zh_label: "Malaysia (+60)" },
  { key: "Maldives (+960)", value: "Maldives (+960)", en_label: "Maldives (+960)", zh_label: "Maldives (+960)" },
  { key: "Mali (+223)", value: "Mali (+223)", en_label: "Mali (+223)", zh_label: "Mali (+223)" },
  { key: "Malta (+356)", value: "Malta (+356)", en_label: "Malta (+356)", zh_label: "Malta (+356)" },
  { key: "Marshall Islands (+692)", value: "Marshall Islands (+692)", en_label: "Marshall Islands (+692)", zh_label: "Marshall Islands (+692)" },
  { key: "Martinique (+596)", value: "Martinique (+596)", en_label: "Martinique (+596)", zh_label: "Martinique (+596)" },
  { key: "Mauritania (+222)", value: "Mauritania (+222)", en_label: "Mauritania (+222)", zh_label: "Mauritania (+222)" },
  { key: "Mauritius (+230)", value: "Mauritius (+230)", en_label: "Mauritius (+230)", zh_label: "Mauritius (+230)" },
  { key: "Mayotte (+262)", value: "Mayotte (+262)", en_label: "Mayotte (+262)", zh_label: "Mayotte (+262)" },
  { key: "Mexico (+52)", value: "Mexico (+52)", en_label: "Mexico (+52)", zh_label: "Mexico (+52)" },
  { key: "Moldova (+373)", value: "Moldova (+373)", en_label: "Moldova (+373)", zh_label: "Moldova (+373)" },
  { key: "Monaco (+377)", value: "Monaco (+377)", en_label: "Monaco (+377)", zh_label: "Monaco (+377)" },
  { key: "Mongolia (+976)", value: "Mongolia (+976)", en_label: "Mongolia (+976)", zh_label: "Mongolia (+976)" },
  { key: "Montenegro (+382)", value: "Montenegro (+382)", en_label: "Montenegro (+382)", zh_label: "Montenegro (+382)" },
  { key: "Montserrat (+1)", value: "Montserrat (+1)", en_label: "Montserrat (+1)", zh_label: "Montserrat (+1)" },
  { key: "Morocco (+212)", value: "Morocco (+212)", en_label: "Morocco (+212)", zh_label: "Morocco (+212)" },
  { key: "Mozambique (+258)", value: "Mozambique (+258)", en_label: "Mozambique (+258)", zh_label: "Mozambique (+258)" },
  { key: "Myanmar (+95)", value: "Myanmar (+95)", en_label: "Myanmar (+95)", zh_label: "Myanmar (+95)" },
  { key: "Namibia (+264)", value: "Namibia (+264)", en_label: "Namibia (+264)", zh_label: "Namibia (+264)" },
  { key: "Nauru (+674)", value: "Nauru (+674)", en_label: "Nauru (+674)", zh_label: "Nauru (+674)" },
  { key: "Nepal (+977)", value: "Nepal (+977)", en_label: "Nepal (+977)", zh_label: "Nepal (+977)" },
  { key: "Netherlands (+31)", value: "Netherlands (+31)", en_label: "Netherlands (+31)", zh_label: "Netherlands (+31)" },
  { key: "Netherlands Antilles (+0)", value: "Netherlands Antilles (+0)", en_label: "Netherlands Antilles (+0)", zh_label: "Netherlands Antilles (+0)" },
  { key: "New Caledonia (+687)", value: "New Caledonia (+687)", en_label: "New Caledonia (+687)", zh_label: "New Caledonia (+687)" },
  { key: "New Zealand (+64)", value: "New Zealand (+64)", en_label: "New Zealand (+64)", zh_label: "New Zealand (+64)" },
  { key: "Nicaragua (+505)", value: "Nicaragua (+505)", en_label: "Nicaragua (+505)", zh_label: "Nicaragua (+505)" },
  { key: "Niger (+227)", value: "Niger (+227)", en_label: "Niger (+227)", zh_label: "Niger (+227)" },
  { key: "Nigeria (+234)", value: "Nigeria (+234)", en_label: "Nigeria (+234)", zh_label: "Nigeria (+234)" },
  { key: "Niue (+683)", value: "Niue (+683)", en_label: "Niue (+683)", zh_label: "Niue (+683)" },
  { key: "Norfolk Island (+672)", value: "Norfolk Island (+672)", en_label: "Norfolk Island (+672)", zh_label: "Norfolk Island (+672)" },
  { key: "Northern Mariana Islands (+1)", value: "Northern Mariana Islands (+1)", en_label: "Northern Mariana Islands (+1)", zh_label: "Northern Mariana Islands (+1)" },
  { key: "Norway (+47)", value: "Norway (+47)", en_label: "Norway (+47)", zh_label: "Norway (+47)" },
  { key: "Pakistan (+92)", value: "Pakistan (+92)", en_label: "Pakistan (+92)", zh_label: "Pakistan (+92)" },
  { key: "Palau (+680)", value: "Palau (+680)", en_label: "Palau (+680)", zh_label: "Palau (+680)" },
  { key: "Palestinian Territory (+970)", value: "Palestinian Territory (+970)", en_label: "Palestinian Territory (+970)", zh_label: "Palestinian Territory (+970)" },
  { key: "Panama (+507)", value: "Panama (+507)", en_label: "Panama (+507)", zh_label: "Panama (+507)" },
  { key: "Papua New Guinea (+675)", value: "Papua New Guinea (+675)", en_label: "Papua New Guinea (+675)", zh_label: "Papua New Guinea (+675)" },
  { key: "Paraguay (+595)", value: "Paraguay (+595)", en_label: "Paraguay (+595)", zh_label: "Paraguay (+595)" },
  { key: "Peru (+51)", value: "Peru (+51)", en_label: "Peru (+51)", zh_label: "Peru (+51)" },
  { key: "Philippines (+63)", value: "Philippines (+63)", en_label: "Philippines (+63)", zh_label: "Philippines (+63)" },
  { key: "Pitcairn (+0)", value: "Pitcairn (+0)", en_label: "Pitcairn (+0)", zh_label: "Pitcairn (+0)" },
  { key: "Poland (+48)", value: "Poland (+48)", en_label: "Poland (+48)", zh_label: "Poland (+48)" },
  { key: "Portugal (+351)", value: "Portugal (+351)", en_label: "Portugal (+351)", zh_label: "Portugal (+351)" },
  { key: "Puerto Rico (+1)", value: "Puerto Rico (+1)", en_label: "Puerto Rico (+1)", zh_label: "Puerto Rico (+1)" },
  { key: "Qatar (+974)", value: "Qatar (+974)", en_label: "Qatar (+974)", zh_label: "Qatar (+974)" },
  { key: "Reunion (+262)", value: "Reunion (+262)", en_label: "Reunion (+262)", zh_label: "Reunion (+262)" },
  { key: "Romania (+40)", value: "Romania (+40)", en_label: "Romania (+40)", zh_label: "Romania (+40)" },
  { key: "Russian Federation (+7)", value: "Russian Federation (+7)", en_label: "Russian Federation (+7)", zh_label: "Russian Federation (+7)" },
  { key: "Rwanda (+250)", value: "Rwanda (+250)", en_label: "Rwanda (+250)", zh_label: "Rwanda (+250)" },
  { key: "S. Georgia and S. Sandwich Islands (+0)", value: "S. Georgia and S. Sandwich Islands (+0)", en_label: "S. Georgia and S. Sandwich Islands (+0)", zh_label: "S. Georgia and S. Sandwich Islands (+0)" },
  { key: "Saint Helena (+290)", value: "Saint Helena (+290)", en_label: "Saint Helena (+290)", zh_label: "Saint Helena (+290)" },
  { key: "Saint Kitts and Nevis (+1)", value: "Saint Kitts and Nevis (+1)", en_label: "Saint Kitts and Nevis (+1)", zh_label: "Saint Kitts and Nevis (+1)" },
  { key: "Saint Lucia (+1)", value: "Saint Lucia (+1)", en_label: "Saint Lucia (+1)", zh_label: "Saint Lucia (+1)" },
  { key: "Saint Pierre and Miquelon (+508)", value: "Saint Pierre and Miquelon (+508)", en_label: "Saint Pierre and Miquelon (+508)", zh_label: "Saint Pierre and Miquelon (+508)" },
  { key: "Saint Vincent and the Grenadines (+1)", value: "Saint Vincent and the Grenadines (+1)", en_label: "Saint Vincent and the Grenadines (+1)", zh_label: "Saint Vincent and the Grenadines (+1)" },
  { key: "Samoa (+685)", value: "Samoa (+685)", en_label: "Samoa (+685)", zh_label: "Samoa (+685)" },
  { key: "San Marino (+378)", value: "San Marino (+378)", en_label: "San Marino (+378)", zh_label: "San Marino (+378)" },
  { key: "Sao Tome and Principe (+239)", value: "Sao Tome and Principe (+239)", en_label: "Sao Tome and Principe (+239)", zh_label: "Sao Tome and Principe (+239)" },
  { key: "Saudi Arabia (+966)", value: "Saudi Arabia (+966)", en_label: "Saudi Arabia (+966)", zh_label: "Saudi Arabia (+966)" },
  { key: "Senegal (+221)", value: "Senegal (+221)", en_label: "Senegal (+221)", zh_label: "Senegal (+221)" },
  { key: "Serbia (+381)", value: "Serbia (+381)", en_label: "Serbia (+381)", zh_label: "Serbia (+381)" },
  { key: "Serbia and Montenegro (+0)", value: "Serbia and Montenegro (+0)", en_label: "Serbia and Montenegro (+0)", zh_label: "Serbia and Montenegro (+0)" },
  { key: "Seychelles (+248)", value: "Seychelles (+248)", en_label: "Seychelles (+248)", zh_label: "Seychelles (+248)" },
  { key: "Sierra Leone (+232)", value: "Sierra Leone (+232)", en_label: "Sierra Leone (+232)", zh_label: "Sierra Leone (+232)" },
  { key: "Singapore (+65)", value: "Singapore (+65)", en_label: "Singapore (+65)", zh_label: "Singapore (+65)" },
  { key: "Slovak Republic (+421)", value: "Slovak Republic (+421)", en_label: "Slovak Republic (+421)", zh_label: "Slovak Republic (+421)" },
  { key: "Slovenia (+386)", value: "Slovenia (+386)", en_label: "Slovenia (+386)", zh_label: "Slovenia (+386)" },
  { key: "Solomon Islands (+677)", value: "Solomon Islands (+677)", en_label: "Solomon Islands (+677)", zh_label: "Solomon Islands (+677)" },
  { key: "Somalia (+252)", value: "Somalia (+252)", en_label: "Somalia (+252)", zh_label: "Somalia (+252)" },
  { key: "South Africa (+27)", value: "South Africa (+27)", en_label: "South Africa (+27)", zh_label: "South Africa (+27)" },
  { key: "South Sudan (+211)", value: "South Sudan (+211)", en_label: "South Sudan (+211)", zh_label: "South Sudan (+211)" },
  { key: "Spain (+34)", value: "Spain (+34)", en_label: "Spain (+34)", zh_label: "Spain (+34)" },
  { key: "Sri Lanka (+94)", value: "Sri Lanka (+94)", en_label: "Sri Lanka (+94)", zh_label: "Sri Lanka (+94)" },
  { key: "Sudan (+249)", value: "Sudan (+249)", en_label: "Sudan (+249)", zh_label: "Sudan (+249)" },
  { key: "Sultanate of Oman (+968)", value: "Sultanate of Oman (+968)", en_label: "Sultanate of Oman (+968)", zh_label: "Sultanate of Oman (+968)" },
  { key: "Suriname (+597)", value: "Suriname (+597)", en_label: "Suriname (+597)", zh_label: "Suriname (+597)" },
  { key: "Svalbard and Jan Mayen (+47)", value: "Svalbard and Jan Mayen (+47)", en_label: "Svalbard and Jan Mayen (+47)", zh_label: "Svalbard and Jan Mayen (+47)" },
  { key: "Swaziland (+268)", value: "Swaziland (+268)", en_label: "Swaziland (+268)", zh_label: "Swaziland (+268)" },
  { key: "Sweden (+46)", value: "Sweden (+46)", en_label: "Sweden (+46)", zh_label: "Sweden (+46)" },
  { key: "Switzerland (+41)", value: "Switzerland (+41)", en_label: "Switzerland (+41)", zh_label: "Switzerland (+41)" },
  { key: "Syria (+963)", value: "Syria (+963)", en_label: "Syria (+963)", zh_label: "Syria (+963)" },
  { key: "Taiwan (+886)", value: "Taiwan (+886)", en_label: "Taiwan (+886)", zh_label: "Taiwan (+886)" },
  { key: "Tajikistan (+992)", value: "Tajikistan (+992)", en_label: "Tajikistan (+992)", zh_label: "Tajikistan (+992)" },
  { key: "Tanzania (+255)", value: "Tanzania (+255)", en_label: "Tanzania (+255)", zh_label: "Tanzania (+255)" },
  { key: "Thailand (+66)", value: "Thailand (+66)", en_label: "Thailand (+66)", zh_label: "Thailand (+66)" },
  { key: "Timor-Leste (+670)", value: "Timor-Leste (+670)", en_label: "Timor-Leste (+670)", zh_label: "Timor-Leste (+670)" },
  { key: "Togo (+228)", value: "Togo (+228)", en_label: "Togo (+228)", zh_label: "Togo (+228)" },
  { key: "Tokelau (+690)", value: "Tokelau (+690)", en_label: "Tokelau (+690)", zh_label: "Tokelau (+690)" },
  { key: "Tonga (+676)", value: "Tonga (+676)", en_label: "Tonga (+676)", zh_label: "Tonga (+676)" },
  { key: "Trinidad and Tobago (+1)", value: "Trinidad and Tobago (+1)", en_label: "Trinidad and Tobago (+1)", zh_label: "Trinidad and Tobago (+1)" },
  { key: "Tunisia (+216)", value: "Tunisia (+216)", en_label: "Tunisia (+216)", zh_label: "Tunisia (+216)" },
  { key: "Turkey (+90)", value: "Turkey (+90)", en_label: "Turkey (+90)", zh_label: "Turkey (+90)" },
  { key: "Turkmenistan (+993)", value: "Turkmenistan (+993)", en_label: "Turkmenistan (+993)", zh_label: "Turkmenistan (+993)" },
  { key: "Turks and Caicos Islands (+1)", value: "Turks and Caicos Islands (+1)", en_label: "Turks and Caicos Islands (+1)", zh_label: "Turks and Caicos Islands (+1)" },
  { key: "Tuvalu (+688)", value: "Tuvalu (+688)", en_label: "Tuvalu (+688)", zh_label: "Tuvalu (+688)" },
  { key: "Uganda (+256)", value: "Uganda (+256)", en_label: "Uganda (+256)", zh_label: "Uganda (+256)" },
  { key: "Ukraine (+380)", value: "Ukraine (+380)", en_label: "Ukraine (+380)", zh_label: "Ukraine (+380)" },
  { key: "United Arab Emirates (+971)", value: "United Arab Emirates (+971)", en_label: "United Arab Emirates (+971)", zh_label: "United Arab Emirates (+971)" },
  { key: "United Kingdom (+44)", value: "United Kingdom (+44)", en_label: "United Kingdom (+44)", zh_label: "United Kingdom (+44)" },
  { key: "Uruguay (+598)", value: "Uruguay (+598)", en_label: "Uruguay (+598)", zh_label: "Uruguay (+598)" },
  { key: "Uzbekistan (+998)", value: "Uzbekistan (+998)", en_label: "Uzbekistan (+998)", zh_label: "Uzbekistan (+998)" },
  { key: "Vanuatu (+678)", value: "Vanuatu (+678)", en_label: "Vanuatu (+678)", zh_label: "Vanuatu (+678)" },
  { key: "Vatican City State (Holy See) (+39)", value: "Vatican City State (Holy See) (+39)", en_label: "Vatican City State (Holy See) (+39)", zh_label: "Vatican City State (Holy See) (+39)" },
  { key: "Venezuela (+58)", value: "Venezuela (+58)", en_label: "Venezuela (+58)", zh_label: "Venezuela (+58)" },
  { key: "Vietnam (+84)", value: "Vietnam (+84)", en_label: "Vietnam (+84)", zh_label: "Vietnam (+84)" },
  { key: "Virgin Islands (British) (+1)", value: "Virgin Islands (British) (+1)", en_label: "Virgin Islands (British) (+1)", zh_label: "Virgin Islands (British) (+1)" },
  { key: "Virgin Islands (U.S.) (+1)", value: "Virgin Islands (U.S.) (+1)", en_label: "Virgin Islands (U.S.) (+1)", zh_label: "Virgin Islands (U.S.) (+1)" },
  { key: "Wallis and Futuna (+681)", value: "Wallis and Futuna (+681)", en_label: "Wallis and Futuna (+681)", zh_label: "Wallis and Futuna (+681)" },
  { key: "Western Sahara (+212)", value: "Western Sahara (+212)", en_label: "Western Sahara (+212)", zh_label: "Western Sahara (+212)" },
  { key: "Yemen (+967)", value: "Yemen (+967)", en_label: "Yemen (+967)", zh_label: "Yemen (+967)" },
  { key: "Zambia (+260)", value: "Zambia (+260)", en_label: "Zambia (+260)", zh_label: "Zambia (+260)" },
  { key: "Zimbabwe (+263)", value: "Zimbabwe (+263)", en_label: "Zimbabwe (+263)", zh_label: "Zimbabwe (+263)" },
];